services:
  micro-ros-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: jazzy
    container_name: micro-ros-agent-container
    stdin_open: true
    tty: true
    volumes:
      # Монтирование рабочего пространства ROS2
      - ./ros2_ws:/ros2_ws
      - /dev:/dev
    environment:
      - ROS_DISTRO=jazzy
      - MICRO_ROS_AGENT_PORT=${MICRO_ROS_AGENT_PORT:-8888}
      - RMW_IMPLEMENTATION=rmw_microxrcedds
    network_mode: host
    privileged: true
    command: udp4 --port ${MICRO_ROS_AGENT_PORT:-8888}

